## Sesi Pagi 

In [1]:
import numpy as np

* Latihan 2

In [2]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A, "\n")
#Lengkapi kodingan berikut
print('banyaknya entry = ', A.size)
print('dimensi array = ', A.ndim)
print('ukuran array = ', A.shape, "\n")

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

banyaknya entry =  9
dimensi array =  2
ukuran array =  (3, 3) 



* Latihan 3

In [3]:
#Lengkapi kodingan berikut
print('baris ke-3 =', A[2])
print('entry ke-1 & 2 baris ke-3 = ', A[2][0:2])
print('entry ke-2 & 3 kolom ke-3 = \n', A[1:3,2:]) #Baris 1-2 kolom >= 2

baris ke-3 = [7 8 9]
entry ke-1 & 2 baris ke-3 =  [7 8]
entry ke-2 & 3 kolom ke-3 = 
 [[6]
 [9]]


* Latihan 4

In [4]:
A = np.array([[1, 2], [7,8]])
B = np.array([[3, 5], [1,6]])
print("Hasil 2xA : \n", 2*A)
print("Hasil 2+A : \n", 2+A)
print("HasilA+B : \n", A+B)
print("HasilA-B : \n", A-B)
print("Hasil det(A) : \n ", np.linalg.det(A))

Hasil 2xA : 
 [[ 2  4]
 [14 16]]
Hasil 2+A : 
 [[ 3  4]
 [ 9 10]]
HasilA+B : 
 [[ 4  7]
 [ 8 14]]
HasilA-B : 
 [[-2 -3]
 [ 6  2]]
Hasil det(A) : 
  -6.0


In [5]:
#invers dari B, simpan jadi matriks D
D = np.linalg.inv(B)
print("D :\n",D, "\n")

#transpose D
print("D^T : \n", D.transpose(), "\n")

#nilai eigen dan vektor eigen dari A dan B
print("Eigen Value A :", np.linalg.eig(A)[0])
print("Eigen Vector A:\n", np.linalg.eig(A)[1],"\n")
print("Eigen Value B :", np.linalg.eig(B)[0])
print("Eigen Vector B:\n", np.linalg.eig(B)[1])

D :
 [[ 0.46153846 -0.38461538]
 [-0.07692308  0.23076923]] 

D^T : 
 [[ 0.46153846 -0.07692308]
 [-0.38461538  0.23076923]] 

Eigen Value A : [-0.62347538  9.62347538]
Eigen Vector A:
 [[-0.77640358 -0.22592838]
 [ 0.63023605 -0.97414391]] 

Eigen Value B : [1.8074176 7.1925824]
Eigen Vector B:
 [[-0.97271381 -0.76626443]
 [ 0.23200828 -0.64252535]]


* Apa perbedaan dari B*D (perkalian antar entry di B dan D) dan BD (perkalian matriks B dan D)?

In [6]:
print("BxD : \n",B*D)
print("BxD : \n",np.matmul(B,D))

BxD : 
 [[ 1.38461538 -1.92307692]
 [-0.07692308  1.38461538]]
BxD : 
 [[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


Perbedaan :

Perkalian entry yang dikalikan pada bilangan baris 1 di matrix B dikalikan bilangan pada baris 1 matrix D, namun pada kolom 2 matric B akan dikalikan kolom 2 matrix D. 

Perkalian matriks yang dikalikan merupakan matrix baris B dengan kolom matrix D dan kolom matrix B dengan baris matrix D

# Sesi Siang

In [11]:
import numpy as np

In [12]:
A = np.array([[1, 2], [7,8]])
B = np.array([[3, 5], [1,6]])

Hitunglah:
- 2*A
- 2+A
- A+B
- A-B
- determinan A
- invers dari B, simpan jadi matriks D
- transpose D
- nilai eigen dan vektor eigen dari A dan B

```
# Ini diformat sebagai kode
```



In [13]:
print(2*A)

[[ 2  4]
 [14 16]]


In [14]:
print(2 + A)

[[ 3  4]
 [ 9 10]]


In [16]:
print(A+B)

[[ 4  7]
 [ 8 14]]


In [17]:
print(A-B)

[[-2 -3]
 [ 6  2]]


In [18]:
print('Determinan', np.linalg.det(A))

Determinan -6.0


In [19]:
D = np.linalg.inv(B)

In [20]:
print(D.transpose())

[[ 0.46153846 -0.07692308]
 [-0.38461538  0.23076923]]


In [21]:
eig_val, eign_vec= np.linalg.eig(A)

In [23]:
print('Eigen Value A = \n',eig_val)

Eigen Value A = 
 [-0.62347538  9.62347538]


In [24]:
print('Eigen Vector A = \n',
      eign_vec)

Eigen Vector A = 
 [[-0.77640358 -0.22592838]
 [ 0.63023605 -0.97414391]]


In [25]:
eig_val, eign_vec= np.linalg.eig(B)

In [26]:
print('Eigen Value B = \n',eig_val)

Eigen Value B = 
 [1.8074176 7.1925824]


In [27]:
print('Eigen Vector B = \n',
      eign_vec)

Eigen Vector B = 
 [[-0.97271381 -0.76626443]
 [ 0.23200828 -0.64252535]]


Apa perbedaan dari B*D (perkalian antar entry di B dan D) dan BD (perkalian matriks B dan D)?

In [28]:
print("perkalian antar entry di B dan D = \n",B*D)

perkalian antar entry di B dan D = 
 [[ 1.38461538 -1.92307692]
 [-0.07692308  1.38461538]]


In [29]:
print("perkalian matriks B dan D = \n",np.matmul(B,D))

perkalian matriks B dan D = 
 [[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]
